#docker-compose build --no-cache 
version: "3"
services:
  nginx:
    image: nginx
    container_name: docker_nginx
    init: true
    links:
      - php
    volumes:
      - ./${FOLDER_NAME}/:/var/www/html/:ro
      - ./nginx/:/etc/nginx/conf.d/
    ports:
      - ${NGINX_PORT}:80

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker_php
    volumes:
      - ./${FOLDER_NAME}/:/var/www/html/
    # command: bash -c "composer require smarty/smarty nikic/fast-route twig/twig vlucas/phpdotenv"
    tmpfs: /tmp
    depends_on:
      - mariadb
    links:
      - mariadb

  mariadb:
    image: mariadb:latest
    container_name: docker_mariadb
    volumes:
      - ./dump/:/docker-entrypoint-initdb.d
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PW}

  phpmyadmin:
    image: phpmyadmin
    container_name: docker_phpmyadmin
    ports:
      - ${PHPMYADMIN_PORT}:80
    links:
      - mariadb:db
    environment:
      - UPLOAD_LIMIT=4800000000000
